### PR TITLE
Richtext text scale factor

### PR DESCRIPTION
**Pull request by ened**
Fixes a issue caused by https://github.com/flutter/flutter/issues/14675

Also adds a little UI test to verify.

### CODE REVIEW

**Comment by alaydeliwala** [comment]
This PR needs to be merged ASAP. This helped me solve my scaling issues :) Thanks

**Comment by ened** [comment]
hi @remoteportal any chance of merging it?

**Comment by ened** [comment]
@remoteportal how are you doing? Are you interested in this PR?

**Comment by remoteportal** [comment]
Version 1.0.25 
Sorry it took so long.
Thank you for contributing, esp. the test!

**Comment by ened** [comment]
Thank you for merging @remoteportal. I have noticed there is a `failures` folder in the test folder now, which should not be there - this indicates problems when running the test. 

Additionally, the PR is merged but the commit history seems to be gone, eliminating the commit & author of the relevant change from the git log.
This is ultimately your decision, just does not seem like the standard way of accepting pull requests around Github.
I noticed the same on other PRs, like #10.

**Pull request closed without merging**
